services:
    youtrack:
        image: jetbrains/youtrack:2025.3.124603
#        volumes:
#            - yt_data:/opt/youtrack/data
#            - conf:/opt/youtrack/conf
#            - logs:/opt/youtrack/logs
#            - backups:/opt/youtrack/backups
        ports:
            - '8080:8080'

#volumes:
#    yt_data:
#    conf:
#    logs:
#    backups:
